[package]
name = "clippings-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
crossbeam-channel.workspace = true
encoding_rs.workspace = true
fancy-regex.workspace = true
globset.workspace = true
grep-matcher.workspace = true
grep-regex.workspace = true
grep-searcher.workspace = true
ignore.workspace = true
lsp-server.workspace = true
memchr.workspace = true
notify.workspace = true
regex.workspace = true
regex-syntax.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
dunce.workspace = true
insta.workspace = true
tempfile.workspace = true
