// Expected views of tests/fixtures/workspace.

/** The default tree view, as `outline` prints it. */
export const DEFAULT_TREE = [
  '(Scan mode: workspace and open files)',
  'workspace',
  '  docs',
  '    plan.md',
  '      [ ] write the guide',
  '      [x] pick a name',
  '  lib',
  '    notes.rs',
  '      TODO first line of a long note',
  '  src',
  '    util',
  '      strings.py',
  '        TODO normalise unicode before comparing',
  '        BUG (bob) drops leading tabs too',
  '    app.ts',
  '      TODO (alice) wire up the router',
  '      FIXME handle the error path',
  '      HACK temporary shim until the router lands',
];

export const FLAT_VIEW = [
  '(Scan mode: workspace and open files)',
  'workspace',
  '  plan.md (docs)',
  '    [ ] write the guide',
  '    [x] pick a name',
  '  notes.rs (lib)',
  '    TODO first line of a long note',
  '  app.ts (src)',
  '    TODO (alice) wire up the router',
  '    FIXME handle the error path',
  '    HACK temporary shim until the router lands',
  '  strings.py (src/util)',
  '    TODO normalise unicode before comparing',
  '    BUG (bob) drops leading tabs too',
];

export const TAGS_ONLY_VIEW = [
  '(Scan mode: workspace and open files)',
  'BUG (bob) drops leading tabs too',
  'HACK temporary shim until the router lands',
  'FIXME handle the error path',
  'TODO first line of a long note',
  'TODO (alice) wire up the router',
  'TODO normalise unicode before comparing',
  '[ ] write the guide',
  '[x] pick a name',
];

/** The tree view grouped by tag. */
export const TREE_GROUPED_BY_TAG = [
  '(Scan mode: workspace and open files)',
  'workspace',
  '  BUG',
  '    src/util',
  '      strings.py',
  '        BUG (bob) drops leading tabs too',
  '  HACK',
  '    src',
  '      app.ts',
  '        HACK temporary shim until the router lands',
  '  FIXME',
  '    src',
  '      app.ts',
  '        FIXME handle the error path',
  '  TODO',
  '    lib',
  '      notes.rs',
  '        TODO first line of a long note',
  '    src',
  '      util',
  '        strings.py',
  '          TODO normalise unicode before comparing',
  '      app.ts',
  '        TODO (alice) wire up the router',
  '  [ ]',
  '    docs',
  '      plan.md',
  '        [ ] write the guide',
  '  [x]',
  '    docs',
  '      plan.md',
  '        [x] pick a name',
];

export const FLAT_GROUPED_BY_TAG = [
  '(Scan mode: workspace and open files)',
  'workspace',
  '  BUG',
  '    strings.py (src/util)',
  '      BUG (bob) drops leading tabs too',
  '  HACK',
  '    app.ts (src)',
  '      HACK temporary shim until the router lands',
  '  FIXME',
  '    app.ts (src)',
  '      FIXME handle the error path',
  '  TODO',
  '    notes.rs (lib)',
  '      TODO first line of a long note',
  '    app.ts (src)',
  '      TODO (alice) wire up the router',
  '    strings.py (src/util)',
  '      TODO normalise unicode before comparing',
  '  [ ]',
  '    plan.md (docs)',
  '      [ ] write the guide',
  '  [x]',
  '    plan.md (docs)',
  '      [x] pick a name',
];

/** Tags only, grouped by tag: a tag with one todo is compacted away. */
export const TAGS_ONLY_GROUPED_BY_TAG = [
  '(Scan mode: workspace and open files)',
  'BUG (bob) drops leading tabs too',
  'HACK temporary shim until the router lands',
  'FIXME handle the error path',
  'TODO',
  '  TODO first line of a long note',
  '  TODO (alice) wire up the router',
  '  TODO normalise unicode before comparing',
  '[ ] write the guide',
  '[x] pick a name',
];
